# Generated by Django 2.1.3 on 2019-04-14 10:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_code',
            new_name='code',
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('user', 'code')},
        ),
    ]
