# Generated by Django 2.1.3 on 2019-04-13 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentopenendedanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Student'),
        ),
        migrations.AddField(
            model_name='studentmatchinganswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Question'),
        ),
        migrations.AddField(
            model_name='studentmatchinganswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Student'),
        ),
        migrations.AddField(
            model_name='studentchoiceanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Question'),
        ),
        migrations.AddField(
            model_name='studentchoiceanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Student'),
        ),
        migrations.AddField(
            model_name='question',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Assignment'),
        ),
        migrations.AddField(
            model_name='openendedkeywords',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Question'),
        ),
        migrations.AddField(
            model_name='membersection',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Student'),
        ),
        migrations.AddField(
            model_name='membersection',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Subject'),
        ),
        migrations.AddField(
            model_name='matchingchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Question'),
        ),
        migrations.AddField(
            model_name='matchinganswer',
            name='choice_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.MatchingChoice'),
        ),
        migrations.AddField(
            model_name='matchinganswer',
            name='item_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Matching'),
        ),
        migrations.AddField(
            model_name='matchinganswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Question'),
        ),
        migrations.AddField(
            model_name='matching',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Question'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Teacher'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Subject'),
        ),
        migrations.AddField(
            model_name='choiceanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Question'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Question'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='studentopenendedanswer',
            unique_together={('question', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='studentmatchinganswer',
            unique_together={('question', 'student', 'answer_item')},
        ),
        migrations.AlterUniqueTogether(
            name='studentchoiceanswer',
            unique_together={('question', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('no', 'assignment')},
        ),
        migrations.AlterUniqueTogether(
            name='openendedkeywords',
            unique_together={('question', 'keyword')},
        ),
        migrations.AlterUniqueTogether(
            name='membersection',
            unique_together={('subject', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='matchingchoice',
            unique_together={('no', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='matchinganswer',
            unique_together={('choice_no', 'item_no', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='matching',
            unique_together={('no', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='lecturer',
            unique_together={('subject', 'lecturer')},
        ),
        migrations.AlterUniqueTogether(
            name='choiceanswer',
            unique_together={('no', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('no', 'question')},
        ),
    ]
