# Generated by Django 2.1.3 on 2019-04-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20190414_1740'),
        ('assignment', '0004_assignment_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudenDoAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='studendoassignment',
            unique_together={('student', 'assignment')},
        ),
    ]
