# Generated by Django 2.1.3 on 2019-04-15 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20190414_1740'),
        ('assignment', '0005_auto_20190415_2017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudenDoAssignment',
            new_name='StudentDoAssignment',
        ),
    ]
