# Generated by Django 2.1.3 on 2019-04-23 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_auto_20190418_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openendedkeywords',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='assignment.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='openendedkeywords',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='openendedkeywords',
            name='id',
        ),
    ]
