# Generated by Django 2.1.3 on 2019-04-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0009_auto_20190423_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openendedkeywords',
            name='keyword',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='studentopenendedanswer',
            name='answer',
            field=models.CharField(max_length=1000),
        ),
    ]
